#!/bin/bash

echo "To push to a private GitHub repository, you'll need to:"
echo ""
echo "1. Create a Personal Access Token on GitHub:"
echo "   - Go to https://github.com/settings/tokens"
echo "   - Click 'Generate new token'"
echo "   - Select 'Fine-grained personal access token' or 'Personal access token (classic)'"
echo "   - Give it a name like 'Automation Website'"
echo "   - Set expiration as needed"
echo "   - Select scopes: 'repo' for private repositories"
echo "   - Copy the generated token"
echo ""
echo "2. After generating your token, run this command:"
echo "   git remote add origin https://github.com/gghhxx11299/ai-automation-website.git"
echo "   git remote set-url origin https://<YOUR_USERNAME>:<YOUR_TOKEN>@github.com/gghhxx11299/ai-automation-website.git"
echo "   git push -u origin main"
echo ""
echo "Alternatively, you can use GitHub CLI:"
echo "   gh repo create ai-automation-website --private"
echo "   git remote add origin https://github.com/gghhxx11299/ai-automation-website.git"
echo "   git push -u origin main"
echo ""
echo "Note: Replace <YOUR_USERNAME> with 'gghhxx11299' and <YOUR_TOKEN> with your actual token."